[package]
name = "slog-gittest"
version = "0.1.0"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]

[dependencies]
slog = { git = "https://github.com/slog-rs/slog" }
slog-json = { git = "https://github.com/slog-rs/slog" }
slog-term = { git = "https://github.com/slog-rs/term" }
slog-scope = { git = "https://github.com/slog-rs/slog" }
slog-stdlog = { git = "https://github.com/slog-rs/slog" }
slog-syslog = { git = "https://github.com/slog-rs/syslog" }
slog-bunyan = { git = "https://github.com/slog-rs/slog" }
slog-atomic = { git = "https://github.com/slog-rs/slog" }
slog-stream = { git = "https://github.com/slog-rs/stream" }
slog-extra  = { git = "https://github.com/slog-rs/extra" }
log = "0.3.6"
lazy_static = "0.1.16"
nix = "0.6.0"

[replace]
"slog:1.2.0" = { git = "https://github.com/slog-rs/slog" }
"slog-stream:1.2.0" = { git = "https://github.com/slog-rs/stream" }
"slog-stream:1.3.1" = { git = "https://github.com/slog-rs/term" }
